GruppoC/force-app/main/default/objects/Conferenza__c/Conferenza__c.object-meta.xml
<CustomObject>
    <label>Conferenza</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conferenze</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GruppoC/force-app/main/default/objects/Conferenza__c/fields/Luogo__c.field-meta.xml
<CustomField>
    <fullName>Luogo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Luogo</label>
    <referenceTo>Luogo__c</referenceTo>
    <relationshipLabel>Conferenze</relationshipLabel>
    <relationshipName>Conferenze</relationshipName>
    <type>Lookup</type>
</CustomField>

GruppoC/force-app/main/default/objects/Conferenza__c/fields/Manifestazione__c.field-meta.xml
<CustomField>
    <fullName>Manifestazione__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manifestazione</label>
    <referenceTo>Manifestazione__c</referenceTo>
    <relationshipLabel>Conferenze</relationshipLabel>
    <relationshipName>Conferenze</relationshipName>
    <type>Lookup</type>
</CustomField>

GruppoC/force-app/main/default/objects/Luogo__c/Luogo__c.object-meta.xml
<CustomObject>
    <label>Luogo</label>
    <nameField>
        <label>Luogo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Luoghi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GruppoC/force-app/main/default/objects/Luogo__c/fields/Indirizzo__c.field-meta.xml
<CustomField>
    <fullName>Indirizzo__c</fullName>
    <label>Indirizzo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

GruppoC/force-app/main/default/objects/Manifestazione__c/Manifestazione__c.object-meta.xml
<CustomObject>
    <label>Manifestazione</label>
    <nameField>
        <label>Nome Manifestazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manifestazione</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GruppoC/force-app/main/default/objects/Manifestazione__c/fields/Luogo__c.field-meta.xml
<CustomField>
    <fullName>Luogo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Luogo</label>
    <referenceTo>Luogo__c</referenceTo>
    <relationshipLabel>Manifestazione</relationshipLabel>
    <relationshipName>Manifestazione</relationshipName>
    <type>Lookup</type>
</CustomField>

GruppoC/force-app/main/default/classes/ConferenceController.cls
public with sharing class ConferenceController {
   
    @AuraEnabled
    public static List<Conferenza__c> getLuoghi(){
        return [select Name,Luogo__r.Name ,Luogo__r.Citta__c,Luogo__r.Indirizzo__c,Luogo__r.Stato__c
         from Conferenza__c];
    }


    @AuraEnabled
    public static List<Conferenza__c> getConferenzePerManifestazione(Id id){
        return [select Name, Luogo__r.Name ,Luogo__r.Citta__c,Luogo__r.Indirizzo__c,Luogo__r.Stato__c
        from Conferenza__c where Manifestazione__r.Id =:id];
    }
}